<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_x</name>
   <tag></tag>
   <elementGuidId>5d9a37f4-8157-4d4a-86d4-124865e434fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='banner_plp_spherical']/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b10721e8-72f7-45c8-8a9e-19ded634531f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>31dd1672-bdc1-4192-a5a7-b57c0f7cc5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner_plp_spherical&quot;)/div[@class=&quot;_3R7eC&quot;]/button[1]</value>
      <webElementGuid>7abd033e-12ba-48df-b77b-7e44e84d0bc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='banner_plp_spherical']/div/button</value>
      <webElementGuid>a0610fa0-a4df-4540-81b7-1fda17f28ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Makanan Kering &amp; Kalengan di Ranch Market Pondok Indah - HappyFresh'])[1]/following::button[1]</value>
      <webElementGuid>76506bbc-5986-46db-bff5-188937d6d1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Makanan Kering &amp; Kalengan'])[1]/preceding::button[2]</value>
      <webElementGuid>5364fba5-6486-4c1d-a537-b116cf4203f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/preceding::button[2]</value>
      <webElementGuid>13a022dd-1198-4fec-ae3b-c47244a697b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>03c4debd-1459-4614-bb03-9fb7d44fd033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3d1415a7-5f90-402b-9414-b8b70b103a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'x' or . = 'x')]</value>
      <webElementGuid>850b7d4e-85b9-4a29-b52f-cfcafeae47e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
