<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>df8966b4-6a11-4df8-80ee-81ed9416c3e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-closable']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>79716669-2081-4a4c-a6d5-a1f4308c5aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/back_22c19.svg</value>
      <webElementGuid>8e3211f6-a17e-43b5-ad0a-35e13c3286e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>16fa6bc7-bbd0-4d14-b462-ed1a37d30db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-closable&quot;)/img[1]</value>
      <webElementGuid>a9c08319-5e4d-4728-8ec0-11a6870bac73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button-closable']/img</value>
      <webElementGuid>7f585379-7c47-4847-9fe4-ad222b6ea5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close']</value>
      <webElementGuid>5a483117-94ae-4826-acfa-773784024c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>26dc1397-283f-42d9-bb52-c759fc819421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/back_22c19.svg' and @alt = 'close']</value>
      <webElementGuid>5d359056-aab7-45d1-822f-dd8957d0da5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
