<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>c4970182-2a62-4c50-9a8d-8c4ca9510d57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='app']/div[2]/div/div/div[2]/div/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e1310d3e-2ec8-49d9-a726-2aa9c6032aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>slots371734</value>
      <webElementGuid>8b42c959-8e57-4dbc-b734-7b64b2e3be7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1eV3R _vCdaA&quot;]/div[@class=&quot;_3ar5_&quot;]/div[1]/div[@class=&quot;_20g8q&quot;]/div[@class=&quot;_LHrA6&quot;]/div[@class=&quot;_2GAF4&quot;]/label[1]</value>
      <webElementGuid>ed61345d-ae0d-4a31-b8f4-0e4565714cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/div[2]/div[3]/label</value>
      <webElementGuid>860d0d9d-afe0-44ac-8999-34c4a31287cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>81468b7f-0706-430f-adfb-c2e5576bd803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
