<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Silakan isi alamat pengantaran</name>
   <tag></tag>
   <elementGuidId>af88ae5a-915b-444d-945b-96f89a143d69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._1uDpz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ace94e7a-8ddb-4274-a654-f55369559dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1uDpz</value>
      <webElementGuid>4ad093f1-1f84-4721-ba4b-3d97d5a5d11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ranch-market-pondok-indah/input-location/focus?from=delivery-page</value>
      <webElementGuid>f2469a86-6fa5-4957-b184-38c74bf1eadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silakan isi alamat pengantaran</value>
      <webElementGuid>56f57146-6d14-4497-a8b0-97ffbdd2885e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1eV3R _vCdaA&quot;]/div[@class=&quot;_1e2I2&quot;]/div[@class=&quot;_3Dwh7&quot;]/div[@class=&quot;_3l3dI&quot;]/div[@class=&quot;_31h7k&quot;]/div[@class=&quot;_cRq2k&quot;]/a[@class=&quot;_1uDpz&quot;]</value>
      <webElementGuid>ca475bd4-4cc3-4ddc-9f82-369e9325f78d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/div/div/a</value>
      <webElementGuid>8abe8683-65e9-47aa-9fa3-5d3f40d9d14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Silakan isi alamat pengantaran')]</value>
      <webElementGuid>6ebe532a-9034-4306-9531-4d81be4544fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Pengantaran'])[1]/following::a[1]</value>
      <webElementGuid>335a73e6-eda7-43b0-a3f7-6b07eea78723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Pengantaran'])[1]/following::a[1]</value>
      <webElementGuid>836c94e1-c24a-4505-b3a3-ad413df583df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[1]</value>
      <webElementGuid>e689bdd7-0c12-45c0-b1d1-ccb0934b1497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Silakan isi alamat pengantaran']/parent::*</value>
      <webElementGuid>2b27694d-a5d6-4d19-aaf3-7047aed543fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ranch-market-pondok-indah/input-location/focus?from=delivery-page')]</value>
      <webElementGuid>1d5615dd-e9d7-49fd-9850-dd22741ec154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ec78a7f2-2b3a-41b9-b13c-af0b5fc6db12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ranch-market-pondok-indah/input-location/focus?from=delivery-page' and (text() = 'Silakan isi alamat pengantaran' or . = 'Silakan isi alamat pengantaran')]</value>
      <webElementGuid>d93c080c-741f-4902-a15c-d880dc7cbeb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
