<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>a9e3e418-8d64-4fb5-8f06-2d628e56efb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='replacement--submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#replacement--submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15b87e4b-195e-4588-ab15-ce688eaf53e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>replacement--submit</value>
      <webElementGuid>6b94e83c-bcd7-4645-9e21-c054195b77e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>cddc9048-03da-40de-a2a2-635f8e5dee1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;replacement--submit&quot;)</value>
      <webElementGuid>2265b67a-6219-4055-a60b-6a0075cd61e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='replacement--submit']</value>
      <webElementGuid>056d5fc6-9e93-462c-a7c3-5d23af49160f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/footer/button</value>
      <webElementGuid>c96802fc-31f1-45e3-ae53-08234d26d4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangan jauh jauh dari telepon Anda, karena pembelanja kami mulai berbelanja.'])[1]/following::button[2]</value>
      <webElementGuid>176732d4-d6c3-4eba-b4b9-e24095f040ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jika salah satu produkmu kehabisan stok, apa yang kamu inginkan dari shopper?'])[1]/following::button[3]</value>
      <webElementGuid>d73ed7b7-83a7-45bb-ace8-0f1dbbeb255a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'replacement--submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>5ae070c5-3bf1-4143-93b6-a683bcd856eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>67037088-2678-4627-aae6-e9a41ab5611c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>fd6b2640-0638-4e2e-9868-c271029fd805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'replacement--submit' and (text() = 'Lanjutkan' or . = 'Lanjutkan')]</value>
      <webElementGuid>3877ed8d-f13c-472d-91f2-954bea9b3478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
