<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mengerti</name>
   <tag></tag>
   <elementGuidId>19421578-480a-41c7-ac8b-d143a78a81be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-modal']/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._8_1hz > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dde21872-30fd-4cdb-95f6-acd62588d391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mengerti</value>
      <webElementGuid>7cde00b9-1bb8-4181-a6f9-aedc5819ffb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-modal&quot;)/div[@class=&quot;_1pNuK&quot;]/div[@class=&quot;_8_1hz&quot;]/button[1]</value>
      <webElementGuid>7fa8b505-bdf4-4c34-bee3-ebabe266a06b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-modal']/div/div/button</value>
      <webElementGuid>2a5e1841-944a-48bb-b441-a00998bb613d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferensi telah disimpan.'])[1]/following::button[1]</value>
      <webElementGuid>6e9163f1-6a0d-4256-96a1-04da1170a93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/following::button[1]</value>
      <webElementGuid>ae723b84-dab4-4ed9-b7c2-eadc37c4e227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mengerti']/parent::*</value>
      <webElementGuid>f2326dc7-73de-402a-8e14-e06c9b0f5404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>c752bbea-29e0-47c7-aa85-7d11eeee2278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Mengerti' or . = 'Mengerti')]</value>
      <webElementGuid>ea0f144b-2f56-43d5-9955-9f3e393d42b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
