<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bayar dengan Aman</name>
   <tag></tag>
   <elementGuidId>35b23d62-531e-4773-8d2b-eb22bdb728bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb7c2d16-b17b-45ce-add6-c8c6f1f7fd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_50IZf</value>
      <webElementGuid>49b4ab25-6e5d-4d49-a778-0d2ae7a13456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-submit</value>
      <webElementGuid>5ca1459d-37c9-4805-acdc-95d1c1ce4c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bayar dengan Aman</value>
      <webElementGuid>3b8a301c-5b4e-4c81-8f41-96377dbb0f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-submit&quot;)</value>
      <webElementGuid>6d802c36-b3af-4be0-ad5e-f7ffcb038121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-submit']</value>
      <webElementGuid>51e0b280-31c3-4d12-99e4-f51d49dd1586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div[2]/div/footer/div/button</value>
      <webElementGuid>4d8c1ab5-caad-4501-8287-e6d8a8c1a109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp133,200'])[1]/following::button[1]</value>
      <webElementGuid>bc933eb6-6a39-40d7-8531-acd95c73ab2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::button[2]</value>
      <webElementGuid>9e6781b7-48a5-4e8e-abf7-240ec80b9a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'button-submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>6033778e-c9fb-4a69-a080-2b6c9853023f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bayar dengan Aman']/parent::*</value>
      <webElementGuid>1e4a266d-5807-4a47-8952-688886f32c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button</value>
      <webElementGuid>36851606-73e3-4c53-aea6-174c26edeef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-submit' and (text() = 'Bayar dengan Aman' or . = 'Bayar dengan Aman')]</value>
      <webElementGuid>1ad7291c-e649-4e92-b69b-7ff86569b596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
