<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pilih Metode Pembayaran__lNlk2</name>
   <tag></tag>
   <elementGuidId>9d958d58-0566-45eb-b8e7-b178202ad6dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payment-method--cod']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._lNlk2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e47b9bb-3017-4f24-b063-364b2fabf060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_lNlk2</value>
      <webElementGuid>0e846ba5-f10c-484a-8edd-79319b8ccf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method--cod&quot;)/div[@class=&quot;_lNlk2&quot;]</value>
      <webElementGuid>773827da-c705-4868-86bb-5b98b38aadb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='payment-method--cod']/div</value>
      <webElementGuid>8fafdd71-8ccb-40cf-8f2b-d58799465a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>0ce341db-619a-4f8d-8b20-6b8123ba0126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
