<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>52673ca9-3635-41d3-83eb-1862a0b5c5ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d597c46e-8ad4-4f20-8792-807970cbbcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b81c960d-5c93-447a-9abd-7afc1b74c7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>nomor rumah/lantai/kamar</value>
      <webElementGuid>1d38440f-679d-4e89-b97c-c8eed8dbe594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1eV3R _vCdaA&quot;]/div[@class=&quot;_1e2I2&quot;]/div[@class=&quot;_3Dwh7&quot;]/div[@class=&quot;_3l3dI&quot;]/div[@class=&quot;_31h7k&quot;]/div[@class=&quot;_cRq2k&quot;]/div[@class=&quot;_ZW4Ud&quot;]/input[1]</value>
      <webElementGuid>9ae3c134-7959-43a0-84a6-1ac5ee1f3090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='']</value>
      <webElementGuid>98fab45c-b521-4cba-8f9f-4c38f4d44f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>ca03fd8d-1fc1-46cc-82cd-1f51f0626d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>abe714d1-78a5-499d-bbbe-80e15b62a4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'nomor rumah/lantai/kamar']</value>
      <webElementGuid>0c373041-41ff-4cb8-891a-bd48e4973120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
