<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>aaf6f69c-8917-47a5-8fcd-121e620150d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[2]/div/div/div[2]/div[1]/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cf4509f4-00b8-4b85-b30f-35f2eebad8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>slots371734</value>
      <webElementGuid>cfcfea5a-c029-477d-8e34-5a596103ec2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1eV3R _vCdaA&quot;]/div[@class=&quot;_3ar5_&quot;]/div[1]/div[@class=&quot;_20g8q&quot;]/div[@class=&quot;_LHrA6&quot;]/div[@class=&quot;_2GAF4&quot;]/label[1]</value>
      <webElementGuid>e074e295-32aa-4f95-a5df-533eb203167e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/div[2]/div[3]/label</value>
      <webElementGuid>a397a596-5c87-4541-a753-4ae576f079a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d652f324-cb9e-412c-855e-cb2e25ffaf77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
