<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>a5bd16e0-aa43-429f-afa1-32a364260c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/div[2]/div/div/div[2]/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button._1FWce</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d1355c4-44e0-46cf-8638-ce7b32fdc9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1FWce</value>
      <webElementGuid>64a97e42-cab2-49ce-9338-5308ef320bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>7547e8ec-ffd7-4c5b-b8a5-5c2df200bd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[3]/div[@class=&quot;on_certain_conditon_to_be_hidden&quot;]/div[@class=&quot;_1L4ze&quot;]/div[@class=&quot;_1tueB&quot;]/div[@class=&quot;_jHV_T&quot;]/div[@class=&quot;_zAMBx&quot;]/button[@class=&quot;_1FWce&quot;]</value>
      <webElementGuid>2b8e56b6-cf20-4acf-9220-7e7596bc0183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div[2]/div/div/div[2]/div[3]/button[2]</value>
      <webElementGuid>3f1b6536-af69-4999-b1eb-8f73a2715a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gunakan lokasimu sekarang'])[1]/following::button[1]</value>
      <webElementGuid>2176ea45-9e3b-49c8-96a9-e02b1cc56f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan lokasimu untuk mendapatkan rekomendasi toko!'])[1]/following::button[2]</value>
      <webElementGuid>d1d144c3-2a22-4af7-9dce-33bf8321fc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belanjaan segar dipilih langsung semudah sentuhan ujung jari'])[1]/preceding::button[1]</value>
      <webElementGuid>5ada45d9-14c4-42b6-aad6-ce0997b25a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangan lewatkan voucher ini!'])[1]/preceding::button[3]</value>
      <webElementGuid>67d9d81d-4b35-44cc-a39d-3a718c92da98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>2c7380ce-f018-4f79-be2b-72b5a9739993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>66a67f7b-13ab-442c-9b20-6c40305050fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>c9ac570b-6d8d-43e4-a9b2-d9bfa2eff590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
