<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7ae7d3d8-e2f7-4241-975b-38a28f6f9d2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[4]/div/a/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Product Display&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8379b415-6c70-4823-8796-0cbb278abfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/default-product_b4cea.png</value>
      <webElementGuid>9267519f-a1ea-45d8-abb3-ded5b5775c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Product Display</value>
      <webElementGuid>acedb14b-9a16-428e-8afd-7ac1f0d85945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;_3I-zn&quot;]/div[@class=&quot;_2lLAH&quot;]/a[1]/figure[@class=&quot;_1_3wR&quot;]/img[1]</value>
      <webElementGuid>75f0483c-1d18-4070-b02f-358f4f36c25d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[4]/div/a/figure/img</value>
      <webElementGuid>85fcb3e5-535e-4bc7-b789-5b2b89f8cae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Product Display']</value>
      <webElementGuid>c82d0212-d4bd-401d-9ce7-d452fbbff65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>07689381-fe56-4edb-a5a7-1413d0b90807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/default-product_b4cea.png' and @alt = 'Product Display']</value>
      <webElementGuid>c9c601dd-68ef-445e-b999-c1b3ef34c3d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
