<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Pengantaran_input-delivery-address</name>
   <tag></tag>
   <elementGuidId>249b6db3-dd3b-4745-ac40-0d24fbde79ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-delivery-address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-delivery-address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4a6513c-6e2a-4275-92ed-30e7910a1df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-delivery-address</value>
      <webElementGuid>db292b73-7ea0-4a60-a706-4620ca102ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94bbf347-a701-45f4-82d3-ec2cb1c1fcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3efBQ</value>
      <webElementGuid>2d1cac66-a628-497a-961b-a287e1cc5db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alamat pengantaran Anda</value>
      <webElementGuid>30deeed0-717c-4b90-9e3b-eed765e26b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>464ab374-27fd-4ed8-859d-74ddf2227e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-delivery-address&quot;)</value>
      <webElementGuid>38ab34a3-c089-42ec-8c15-6b77260f1ff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-delivery-address']</value>
      <webElementGuid>b286d657-479f-45e1-91a7-8b39d6841469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/input</value>
      <webElementGuid>58e33adc-16c2-444a-bba1-1dfb9a895285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>22e2a0f9-a49c-4eea-84b8-74d72c951abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-delivery-address' and @placeholder = 'Masukkan alamat pengantaran Anda' and @type = 'text']</value>
      <webElementGuid>b5df02be-7ca1-4e11-820a-e1f586265b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
