<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_x_header-search-bar</name>
   <tag></tag>
   <elementGuidId>4b699ffb-0ec1-464c-adeb-4698e9282d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='header-search-bar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-search-bar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49350a5b-10cb-4e1b-a20a-6c09ea15471b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-search-bar</value>
      <webElementGuid>a37fae60-af65-410a-b56a-c0f6f80af8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_u8itH _1v0s2</value>
      <webElementGuid>551b0890-5b5d-46ac-860e-ef03d1a547f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari produk di HappyFresh</value>
      <webElementGuid>9b9525a1-fc60-4420-a385-4c74ce907be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-search-bar&quot;)</value>
      <webElementGuid>23ccecd6-4e4f-43f0-a3c1-af450cb737fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='header-search-bar']</value>
      <webElementGuid>ed646b25-0edc-4c1a-badc-58fc091c106b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/nav/div/div[2]/div/a/input</value>
      <webElementGuid>2bc5a779-78c8-44ee-9a42-280bba4572cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/input</value>
      <webElementGuid>68b00aab-88f0-4c3f-890c-38d410f6b3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'header-search-bar' and @placeholder = 'Cari produk di HappyFresh']</value>
      <webElementGuid>45e53de6-28ed-4b94-9ebe-7c89297042be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
