<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ranch Market Pondok Indah_navbar-account</name>
   <tag></tag>
   <elementGuidId>a68645a2-0cd0-4969-b21b-74099bd15db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbar-account']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navbar-account</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62fd451b-f7d6-4bb1-8b1b-e021f9e58e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7cmyO _2AMie</value>
      <webElementGuid>26905d9e-becc-40a3-a7bc-b8c32cf60d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbar-account</value>
      <webElementGuid>dab3f563-ac74-442b-af56-90b36aa455cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ranch-market-pondok-indah/account/</value>
      <webElementGuid>65b4c0be-1a9e-40b0-9d7d-f473b3ea3ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-account&quot;)</value>
      <webElementGuid>d78e84bf-17bc-4b8a-9e6c-02fa5b725bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navbar-account']</value>
      <webElementGuid>ad7a6778-84ef-4a65-950a-7a2c280915f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/header/nav/div[2]/a[3]</value>
      <webElementGuid>44d33271-e712-49ce-8b39-edcd95918d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ranch-market-pondok-indah/account/')]</value>
      <webElementGuid>6a2efa5b-57c2-4080-b33b-e177589cda62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>297149d3-2ea0-4780-a116-bc357d47bd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'navbar-account' and @href = '/ranch-market-pondok-indah/account/']</value>
      <webElementGuid>1abcd126-0da3-487d-b019-d347defab6cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
