<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah</name>
   <tag></tag>
   <elementGuidId>9e188225-f14a-4325-81ad-5e65fae155ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-add-117641']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-add-117641</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1cf56e72-76b2-4734-81cb-b3bf36f36d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-add-117641</value>
      <webElementGuid>8079a139-fe99-4f7c-b649-ada4af884b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2tD_-</value>
      <webElementGuid>c5bcdce9-ff57-448c-9f21-8adafb6b8b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Tambah</value>
      <webElementGuid>bf3158cd-e429-42f7-aa2c-c45850eb10f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-add-117641&quot;)</value>
      <webElementGuid>d5265b2c-6c83-42f2-b6fa-b59863482e6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-add-117641']</value>
      <webElementGuid>f303c060-a992-4dc0-b0a9-4ddcac612baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/section/div/div[2]/div/div/div/div/div[2]/div[4]/button</value>
      <webElementGuid>6810004b-b55a-4fd4-bd08-b2b759b53163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp17,900 / 100 ml'])[1]/following::button[1]</value>
      <webElementGuid>ecdeb592-ce9b-43f7-adc8-f7d6d8e2ad28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp71,500'])[1]/following::button[1]</value>
      <webElementGuid>1ceeebfa-255e-4613-8bc9-4c21ad917138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>fc3529d2-7532-443b-af6e-9e770a1d9c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-add-117641' and (text() = '+Tambah' or . = '+Tambah')]</value>
      <webElementGuid>4db4cf82-c1b4-4e30-8688-64958964313f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
