<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3</name>
   <tag></tag>
   <elementGuidId>94d227c8-b1cf-4059-9f70-09c0235afd80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icon-cart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c43fe62b-4681-4453-bed9-b8af5f253f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2hIiY _3-KYx _1pE5F</value>
      <webElementGuid>d14893b5-7c66-4671-9b52-6693781ff5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-cart</value>
      <webElementGuid>56ba0899-38c2-4968-a600-25fd66d19898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ranch-market-pondok-indah/cart</value>
      <webElementGuid>a7fefe62-09bc-4e5d-a6fe-8577247aacf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c50ab131-d30d-49ef-9767-d695c2487a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-cart&quot;)</value>
      <webElementGuid>1a31d9eb-c5fc-4ad3-bd7a-0fcd336f6b84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icon-cart']</value>
      <webElementGuid>755c88d6-5b62-40bf-a628-379bb8c17c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/header/nav/div[2]/a[4]</value>
      <webElementGuid>c676f79c-0b4b-4a25-934a-6f18e841cbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranch Market Pondok Indah'])[1]/following::a[5]</value>
      <webElementGuid>e76522c6-6488-4038-aec0-d7e8ebddf094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::a[6]</value>
      <webElementGuid>694e0627-46b6-4c16-ae69-aca2acfb3825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diantar ke'])[1]/preceding::a[1]</value>
      <webElementGuid>30676270-3208-4729-9232-3a4694cb6650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan alamat pengantaran Anda'])[1]/preceding::a[1]</value>
      <webElementGuid>a23f78c3-a67e-4d20-bc90-fe71d3caead9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ranch-market-pondok-indah/cart')]</value>
      <webElementGuid>45cab86a-2933-49a8-b6fc-c754514d8715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>b5d663b5-ea2b-4afd-ad15-43beca14c5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'icon-cart' and @href = '/ranch-market-pondok-indah/cart' and (text() = '3' or . = '3')]</value>
      <webElementGuid>51913f30-0e36-4f03-b686-36baa1945a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
