<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_x</name>
   <tag></tag>
   <elementGuidId>3dd5698a-0e6b-4af0-8a3a-24e39c766e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='banner_order_detail_modal']/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._3R7eC > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3de4c5e1-b5a3-4f5a-a680-14cd7c0c15db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>8115496f-df4d-4b37-9bdb-51cb0de3caac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner_order_detail_modal&quot;)/div[@class=&quot;_3R7eC&quot;]/button[1]</value>
      <webElementGuid>08c193a5-7515-46a3-a2f2-e144b27e9797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='banner_order_detail_modal']/div/button</value>
      <webElementGuid>53c0bd2e-82d7-4311-92e5-1d7040699713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GET'])[1]/following::button[1]</value>
      <webElementGuid>c53df0cd-04df-4ef5-b20c-e28beb2a6d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[1]/following::button[2]</value>
      <webElementGuid>8ef90933-4840-43f7-b6a9-32a70009bf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Pesanan'])[1]/preceding::button[2]</value>
      <webElementGuid>85ec9409-c066-45bc-8b7c-2bb7d5b79de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Pesanan: R633335168'])[1]/preceding::button[2]</value>
      <webElementGuid>6914b09b-6868-44fc-92a8-8a9732b01a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>87d4efa3-82a7-43a1-adea-b428b420cce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'x' or . = 'x')]</value>
      <webElementGuid>527132bd-7dd9-4f90-9784-a95f976bc6da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
