<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tidak-Halal__2OlBL</name>
   <tag></tag>
   <elementGuidId>ece512fa-322b-4173-b02c-bd0d653adde7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/div[2]/div/div/a[4]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3dcccd6-88d6-4843-8dc2-8d6fc439ae62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2OlBL</value>
      <webElementGuid>7811d29f-c40f-4a5b-938e-34bdcd6e2085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.happyfresh.com/t/s_product,c_fit/spree/taxon_display_images/display_images/af664400556be7b5bf95508068c6c895c004353b-original.jpg</value>
      <webElementGuid>00614810-3891-40ab-9d0a-920d847c2fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Makanan Kering &amp; Kalengan</value>
      <webElementGuid>f5b2c09c-822b-4165-98a6-d2ba6bc0ec75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>defaultstyle</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>213d0c35-4db6-4c75-8bed-501676a56e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>withlazyload</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc985ae3-6a31-4ee4-bc52-a9f638797b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1eV3R&quot;]/div[@class=&quot;_3dD5g&quot;]/div[2]/div[@class=&quot;_2cB2B&quot;]/div[@class=&quot;_3UA8p _3CZ2p&quot;]/a[4]/div[@class=&quot;_3B8K0&quot;]/img[@class=&quot;_2OlBL&quot;]</value>
      <webElementGuid>9a153c46-cb72-4e44-97cd-dfd0029ba6c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div[2]/div/div/a[4]/div/img</value>
      <webElementGuid>de410677-3347-4339-aaa0-aa9388b21640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Makanan Kering &amp; Kalengan']</value>
      <webElementGuid>eb30cf9a-ab07-47f0-899f-f6da98433907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/img</value>
      <webElementGuid>f61073f7-eb0e-411f-ab49-4fa7e8022128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.happyfresh.com/t/s_product,c_fit/spree/taxon_display_images/display_images/af664400556be7b5bf95508068c6c895c004353b-original.jpg' and @alt = 'Makanan Kering &amp; Kalengan']</value>
      <webElementGuid>d51b9d91-5316-4f30-8b71-985cfa101aec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
